# contracts.py
"""Structural-typing contracts for the Launchpad95 control surface.

These protocols name the interfaces that *our* code depends on. They are
defined under TYPE_CHECKING so this module executes nothing at runtime:
zero footprint, zero behavior change, and identical behavior whether the
script runs on a 3.7-era or a 3.11-era Live. (typing.Protocol is importable
at runtime on 3.8+, but a remote script that crashes takes the controller
down with it; static-only contracts carry no such risk.)

_Framework types appear as `Any` because the decompiled _Framework sources
contain syntax errors and cannot be parsed by a type checker.
"""
from __future__ import annotations

from contextlib import contextmanager
from typing import TYPE_CHECKING, Any, Callable, Iterator, List, Optional, Tuple

if TYPE_CHECKING:
    from typing import Protocol, runtime_checkable

    # ------------------------------------------------------------------
    # 1. Host boundary (responsibility 1)
    # ------------------------------------------------------------------
    @runtime_checkable
    class HostApi(Protocol):
        """The full surface of Ableton's Live.MidiRemoteScript (c_instance)
        that this project uses. The one seam between our code and Live."""
        def send_midi(self, midi_bytes: bytes) -> None: ...
        def show_message(self, message: str) -> None: ...
        def log_message(self, message: str) -> None: ...
        def request_rebuild_midi_map(self) -> None: ...
        def set_pad_translation(self, translations: Any) -> None: ...
        def set_session_highlight(self, track_offset: int, scene_offset: int,
                                  width: int, height: int,
                                  include_return_tracks: bool) -> None: ...
        def toggle_lock(self) -> None: ...
        def update_locks(self) -> None: ...
        def set_feedback_channels(self, channels: Any) -> None: ...
        def set_feedback_velocity(self, velocity: int) -> None: ...
        def set_controlled_track(self, track: Any) -> None: ...
        def release_controlled_track(self) -> None: ...
        def instance_identifier(self) -> int: ...
        def handle(self) -> int: ...
        def song(self) -> Any: ...
        def note_repeat(self) -> Any: ...

    # ------------------------------------------------------------------
    # 3+4. MIDI transport (responsibilities 3, 4)
    # ------------------------------------------------------------------
    class MidiTransport(Protocol):
        def send(self, midi_bytes: bytes, optimized: bool = True) -> bool: ...
        def receive(self, midi_bytes: bytes) -> None: ...
        def is_sysex(self, midi_bytes: bytes) -> bool: ...

    class MidiDispatcher(Protocol):
        """Routes incoming bytes to registered input controls."""
        def handle_nonsysex(self, midi_bytes: bytes) -> None: ...
        def handle_sysex(self, midi_bytes: bytes) -> None: ...

    # ------------------------------------------------------------------
    # 5. MIDI map management (responsibility 5)
    # ------------------------------------------------------------------
    class MidiMapManager(Protocol):
        def request_rebuild(self) -> None: ...
        def build(self, midi_map_handle: int) -> None: ...
        def set_pad_translations(self, translations: Any) -> None: ...
        def suggest_input_port(self) -> str: ...
        def suggest_output_port(self) -> str: ...
        def suggest_map_mode(self, cc_no: int, channel: int) -> int: ...
        def suggest_needs_takeover(self, cc_no: int, channel: int) -> bool: ...
        @contextmanager
        def suppressing_rebuild_requests(self) -> Iterator[None]: ...

    # ------------------------------------------------------------------
    # 6. Component registry + lifecycle (responsibility 6)
    # ------------------------------------------------------------------
    class ComponentRegistry(Protocol):
        def register_component(self, component: Any) -> None: ...   # ControlSurfaceComponent
        def register_control(self, control: Any) -> None: ...       # ControlElement
        @property
        def components(self) -> Tuple[Any, ...]: ...
        @property
        def root_components(self) -> Tuple[Any, ...]: ...
        @property
        def controls(self) -> List[Any]: ...
        def get_control_by_name(self, name: str) -> Optional[Any]: ...
        def disconnect_all(self) -> None: ...

    class ComponentLifecycle(Protocol):
        def update(self) -> None: ...
        def refresh_state(self) -> None: ...
        def set_enabled(self, enable: bool) -> None: ...
        def disconnect(self) -> None: ...

    # ------------------------------------------------------------------
    # 7. Task / time management (responsibility 7)
    # ------------------------------------------------------------------
    class TaskScheduler(Protocol):
        def schedule_message(self, delay_in_ticks: int,
                             callback: Callable[[], None],
                             parameter: Any = None) -> None: ...
        def update(self, delta: int) -> None: ...
        def clear(self) -> None: ...

    # ------------------------------------------------------------------
    # 8. Host-state observation (responsibility 8) — component side
    # ------------------------------------------------------------------
    class SongStateListener(Protocol):
        """What the surface broadcasts to each registered component."""
        def on_track_list_changed(self) -> None: ...
        def on_scene_list_changed(self) -> None: ...
        def on_selected_track_changed(self) -> None: ...
        def on_selected_scene_changed(self) -> None: ...

    # ------------------------------------------------------------------
    # 9+10. Device locks, session highlighting (responsibilities 9, 10)
    # ------------------------------------------------------------------
    class DeviceLockManager(Protocol):
        def set_device_component(self, component: Optional[Any]) -> None: ...  # DeviceComponent
        def can_lock_to_devices(self) -> bool: ...
        def lock_to_device(self, device: Any) -> None: ...
        def unlock_from_device(self, device: Any) -> None: ...
        def restore_bank(self, bank_index: int) -> None: ...

    class SessionHighlighter(Protocol):
        def set_highlighting_session_component(self, comp: Optional[Any]) -> None: ...  # SessionComponent
        def highlighting_session_component(self) -> Optional[Any]: ...

    # ------------------------------------------------------------------
    # 11. Re-entrancy guarding (responsibility 11)
    # ------------------------------------------------------------------
    class ReentrancyGuard(Protocol):
        @contextmanager
        def component_guard(self) -> Iterator[None]: ...
        @property
        def in_component_guard(self) -> bool: ...
        @contextmanager
        def accumulating_midi_messages(self) -> Iterator[None]: ...
        @contextmanager
        def suppressing_rebuild_requests(self) -> Iterator[None]: ...

    # ------------------------------------------------------------------
    # Aggregate facade: what our components may call on the surface
    # ------------------------------------------------------------------
    class ControlSurfaceFacade(Protocol):
        """Union of the ports our components actually use. Type component
        constructor parameters against this (or a narrower protocol above)
        instead of the concrete _Framework.ControlSurface."""
        host_api: HostApi
        @property
        def controls(self) -> List[Any]: ...
        def show_message(self, message: str) -> None: ...
        def log_message(self, *message: Any) -> None: ...
        def schedule_message(self, delay_in_ticks: int,
                             callback: Callable[[], None],
                             parameter: Any = None) -> None: ...
        def request_rebuild_midi_map(self) -> None: ...
        def set_enabled(self, enable: bool) -> None: ...
        def update(self) -> None: ...
        def disconnect(self) -> None: ...
        def get_control_by_name(self, name: str) -> Optional[Any]: ...
        @contextmanager
        def component_guard(self) -> Iterator[None]: ...
