# Decompiled with pycdc from Ableton Live 12 (Python 3.11).
# Some functions may be partial: pycdc cannot fully decompile 3.11 bytecode.

# Source Generated with Decompyle++
# File: custom_bank_definitions.pyc (Python 3.11)

from copy import deepcopy
from ableton.v2.base.collection import IndexedDict
from ableton.v3.control_surface import BANK_DEFINITIONS, BANK_MAIN_KEY, BANK_PARAMETERS_KEY
from ableton.v3.live import liveobj_valid
from banking_util import use
from display_util import ELLIPSIS_CHAR
SHIFTED_PARAMETER_MAPPINGS = {
    'AutoShift': ('Pitch Fine', 'Formant Follow', 'Pitch Scale Deg.', 'Vibrato Rate'),
    'DrumCell': ('Detune', 'Length', 'Vel > Vol'),
    'OriginalSimpler': ('Detune', 'L Rate', 'L Sync Rate', 'S Length') }

def is_shifted_parameter_mapping(device_name, parameter):
    if liveobj_valid(parameter):
        pass
    return parameter.original_name in SHIFTED_PARAMETER_MAPPINGS.get(device_name, ())

CUSTOM_BANK_DEFINITIONS = deepcopy(BANK_DEFINITIONS)
CUSTOM_BANK_DEFINITIONS['AutoFilter2'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: (use('Control').if_parameter('Filter Type').has_value('DJ').else_use('Pitch').if_parameter('Filter Type').has_value('Vowel').else_use('Frequency'), use('Filter Morph').if_parameter('Filter Type').has_value('Morph').else_use('Formant').if_parameter('Filter Type').has_value('Vowel').else_use('Resonance'), 'Filter Type', 'Drive', 'LFO Wave', 'LFO Amount', use('LFO Freq').if_parameter('LFO T Mode').has_value('Rate').else_use('LFO Time').if_parameter('LFO T Mode').has_value('Time').else_use('LFO 16th').if_parameter('LFO T Mode').has_value('Sixteenth').else_use('LFO Rate'), 'Dry/Wet') }),))
CUSTOM_BANK_DEFINITIONS['AutoPan2'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: ('Amount', use('Frequency').if_parameter('Time Mode').has_value('Rate').else_use('Time').if_parameter('Time Mode').has_value('Time').else_use('16th').if_parameter('Time Mode').has_value('16th').else_use('Rate'), 'Time Mode', use('Waveform').if_parameter('Mode').has_value('Panning').else_use('Invert'), use('Panning Shape').if_parameter('Mode').has_value('Panning').else_use('Tremolo Shape'), use('Harmonic').if_parameter('Mode').has_value('Tremolo').else_use('Phase').if_parameter('Stereo Mode').has_value('Phase').else_use('Spin'), 'Attack Time', use('Dyn Mod').with_name('Dynamic Mod')) }),))
CUSTOM_BANK_DEFINITIONS['AutoShift'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: ('Strength', use('Smooth Time').with_name('Smooth'), use('Pitch St.').with_name('Shift Semitones').if_shift(False).else_use('Pitch Fine').with_name('Detune'), use('Formant Shift').if_shift(False).else_use('Formant Follow'), use('Vibrato Amt').with_name('Vibrato Amount').if_shift(False).else_use('Vibrato Rate'), 'Root', use('Scale').if_shift(False).else_use('Pitch Scale Deg.').with_name('Shift Scale'), 'Dry/Wet') }),))
CUSTOM_BANK_DEFINITIONS['ChannelEq'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: ('Low Gain', 'Mid Gain', use('Mid Freq').with_name('Mid Frequency'), 'High Gain', use('Highpass On').with_name('High-Pass'), 'Output', '', '') }),))
CUSTOM_BANK_DEFINITIONS['Chorus2'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: ('Mode', 'Rate', 'Amount', use('Shape').if_parameter('Mode').has_value('Vibrato').else_use('Feedback'), use('HP Freq').with_name('High-Pass Freq'), use('').if_parameter('Mode').has_value('Vibrato').else_use('Width'), 'Warmth', 'Dry/Wet') }),))
CUSTOM_BANK_DEFINITIONS['Delay'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: (use('L 16th').with_name('Time in 16ths').if_parameter('L Sync').has_value('On').else_use('L Time').with_name('Time'), 'Feedback', use('Filter Freq').with_name('Filter Frequency'), 'Filter Width', use('LFO Freq').with_name('Modulation Freq'), use('LFO > Filter').with_name('Filter Modulation'), use('LFO > Delay').with_name('Time Modulation'), 'Dry/Wet') }),))
CUSTOM_BANK_DEFINITIONS['Drift'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: (use('Osc 1 Wave').with_name('Osc 1 Waveform'), 'Osc 1 Shape', 'Osc 1 Gain', 'Osc 2 Gain', use('LP Freq').with_name('Low-Pass Filter'), use('LP Res').with_name('Low-Pass Reso'), 'Env 1 Attack', 'Env 1 Release') }), ('Oscillators', {
    BANK_PARAMETERS_KEY: (use('Osc 1 Wave').with_name('Osc 1 Waveform'), use('Osc 1 Oct').with_name('Osc 1 Octave'), 'Osc 1 Shape', 'Osc 1 Gain', use('Osc 2 Wave').with_name('Osc 2 Waveform'), use('Osc 2 Oct').with_name('Osc 2 Octave'), 'Osc 2 Shape', 'Osc 2 Gain') }), ('Osc Mod', {
    BANK_PARAMETERS_KEY: (use('Pitch Mod Src 1').with_name('Mod-1 Source'), use('Pitch Mod Amt 1').with_name('Pitch Mod-1'), use('Pitch Mod Src 2').with_name('Mod-2 Source'), use('Pitch Mod Amt 2').with_name('Pitch Mod-2'), use('Shape Mod Src').with_name('Mod Source'), use('Osc 1 Shape Mod Amt').with_name('Osc 1 Shape Mod'), use('Osc Retrig On').with_name('Phase Reset'), 'Noise Gain') }), ('Filters', {
    BANK_PARAMETERS_KEY: (use('LP Freq').with_name('Low-Pass Filter'), use('LP Res').with_name('Low-Pass Reso'), use('LP Type').with_name('Low-Pass Type'), use('HP Freq').with_name('High-Pass Filter'), use('Osc 1 Flt On').with_name('Filter Osc 1'), use('Osc 2 Flt On').with_name('Filter Osc 2'), use('Noise On').with_name('Filter Noise'), '') }), ('Filter Mod', {
    BANK_PARAMETERS_KEY: (use('Key > LPF').with_name('Key > Low-Pass'), use('LP Mod Src 1').with_name('Mod-1 Source'), use('LP Mod Amt 1').with_name('Low-Pass Mod-1'), use('LP Mod Src 2').with_name('Mod-2 Source'), use('LP Mod Amt 2').with_name('Low-Pass Mod-2'), '', '', '') }), ('Envelope 1', {
    BANK_PARAMETERS_KEY: ('Env 1 Attack', 'Env 1 Decay', 'Env 1 Sustain', 'Env 1 Release', '', '', '', '') }), ('Envelope 2', {
    BANK_PARAMETERS_KEY: (use('Env 2 Attack').if_parameter('Env 2 Cyc On').has_value('Env').else_use('Cyc Env Tilt').with_name('Cycling Tilt'), use('Env 2 Decay').if_parameter('Env 2 Cyc On').has_value('Env').else_use('Cyc Env Hold').with_name('Cycling Hold'), use('Env 2 Sustain').if_parameter('Env 2 Cyc On').has_value('Env').else_use('Cyc Env Rate').with_name('Cycling Rate').if_parameter('Cyc Env Time Mode').has_value('Freq').else_use('Cyc Env Time').with_name('Cycling Time').if_parameter('Cyc Env Time Mode').has_value('Time').else_use('Cyc Env Ratio').with_name('Cycling Ratio').if_parameter('Cyc Env Time Mode').has_value('Ratio').else_use('Cyc Env Synced').with_name('Cycling Sync'), use('Env 2 Release').if_parameter('Env 2 Cyc On').has_value('Env').else_use('Cyc Env Time Mode').with_name('Cycling Mode'), use('Env 2 Cyc On').with_name('Envelope 2 Mode'), '', '', '') }), ('LFO', {
    BANK_PARAMETERS_KEY: (use('LFO Wave').with_name('LFO Waveform'), 'LFO Time Mode', use('LFO Rate').if_parameter('LFO Time Mode').has_value('Freq').else_use('LFO Time').if_parameter('LFO Time Mode').has_value('Time').else_use('LFO Ratio').if_parameter('LFO Time Mode').has_value('Ratio').else_use('LFO Synced'), use('LFO Amt').with_name('LFO Amount'), use('LFO Retrig On').with_name('LFO Retrigger'), use('LFO Mod Src').with_name('LFO Mod Source'), use('LFO Mod Amt').with_name('LFO Modulation'), '') }), ('Mod 1 & 2', {
    BANK_PARAMETERS_KEY: (use('Mod Source 1').with_name('Mod-1 Source'), use('Mod Dest 1').with_name('Mod-1 Target'), use('Mod Matrix Amt 1').with_name('Mod-1 Amount'), use('Mod Source 2').with_name('Mod-2 Source'), use('Mod Dest 2').with_name('Mod-2 Target'), use('Mod Matrix Amt 2').with_name('Mod-2 Amount'), '', '') }), ('Mod 3', {
    BANK_PARAMETERS_KEY: (use('Mod Source 3').with_name('Mod-3 Source'), use('Mod Dest 3').with_name('Mod-3 Target'), use('Mod Matrix Amt 3').with_name('Mod-3 Amount'), use('Vel > Vol').with_name('Velocity > Vol'), '', '', '', '') }), ('Global', {
    BANK_PARAMETERS_KEY: ('Voice Mode', use('').if_parameter('Voice Mode').has_value('Poly').else_use('Thickness').with_name('Mono Thickness').if_parameter('Voice Mode').has_value('Mono').else_use('Spread').with_name('Stereo Spread').if_parameter('Voice Mode').has_value('Stereo').else_use('Strength').with_name('Unison Strength').if_parameter('Voice Mode').has_value('Unison'), use('Voice Count').with_name('Voices'), 'Drift', use('Legato On').with_name('Legato'), 'Glide Time', 'Transpose', 'Volume') })))
CUSTOM_BANK_DEFINITIONS['DrumCell'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: (use('Transpose').if_shift(False).else_use('Detune'), 'Start', 'Attack', 'Hold', use('Decay').if_shift(False).else_use('Length'), use('FX Type').with_name('Playback Effect'), use('Pitch Env Amt').with_name('Pitch Env Amount').if_parameter('FX Type').has_value('Pitch Env').else_use('Sub Amt').with_name('Sub Amount').if_parameter('FX Type').has_value('Sub Osc').else_use('Noise Amt').with_name('Noise Amount').if_parameter('FX Type').has_value('Noise').else_use('Loop Offset').if_parameter('FX Type').has_value('Loop').else_use('Stretch Factor').if_parameter('FX Type').has_value('Stretch').else_use('Punch Amt').with_name('Punch Amount').if_parameter('FX Type').has_value('Punch').else_use('8-Bit Rate').if_parameter('FX Type').has_value('8-Bit').else_use('FM Amt').with_name('FM Amount').if_parameter('FX Type').has_value('FM').else_use('RM Amt').with_name('Ring Mod Amt'), use('Pitch Env Decay').if_parameter('FX Type').has_value('Pitch Env').else_use('Sub Freq').with_name('Sub Frequency').if_parameter('FX Type').has_value('Sub Osc').else_use('Noise Color').with_name('Noise Frequency').if_parameter('FX Type').has_value('Noise').else_use('Loop Length').if_parameter('FX Type').has_value('Loop').else_use('Grain Size').if_parameter('FX Type').has_value('Stretch').else_use('Punch Release').if_parameter('FX Type').has_value('Punch').else_use('8-Bit Flt Decay').with_name('8-Bit Decay').if_parameter('FX Type').has_value('8-Bit').else_use('FM Freq').with_name('FM Frequency').if_parameter('FX Type').has_value('FM').else_use('RM Freq').with_name('Ring Mod Freq')) }), ('Filter & Setup', {
    BANK_PARAMETERS_KEY: (use('Filter Freq').with_name('Filter Frequency'), use('Filter Gain').if_parameter('Filter Type').has_value('Peak').else_use('Filter Res').with_name('Filter Resonance'), 'Filter Type', use('Env Mode').with_name('Envelope Mode'), '', use('Mod Dest').with_name('Velocity > {}'.format(ELLIPSIS_CHAR)), use('Vel > Vol').with_name('Velocity > Vol').if_shift(True).else_use('Mod Amt').with_name('Velocity > Filter').if_parameter('Mod Dest').has_value('Filter').else_use('Mod Amt').with_name('Velocity > Attack').if_parameter('Mod Dest').has_value('Attack').else_use('Mod Amt').with_name('Velocity > Hold').if_parameter('Mod Dest').has_value('Hold').else_use('Mod Amt').with_name('Velocity > Decay').if_parameter('Mod Dest').has_value('Decay').else_use('Mod Amt').with_name('Velocity > FX 1').if_parameter('Mod Dest').has_value('FX 1').else_use('Mod Amt').with_name('Velocity > FX 2'), 'Pan') })))
CUSTOM_BANK_DEFINITIONS['Erosion2'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: ('Amount', 'Noise Blend', 'Frequency', 'Filter Width', 'Stereo Width', '', '', '') }),))
CUSTOM_BANK_DEFINITIONS['PhaserNew'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: ('Mode', use('Mod Rate').with_name('Rate').if_parameter('Mod Sync').has_value('On').else_use('Mod Freq').with_name('Frequency'), 'Amount', 'Feedback', use('Center Freq').if_parameter('Mode').has_value('Phaser').else_use('Flanger Time').if_parameter('Mode').has_value('Flanger').else_use('Doubler Time').if_parameter('Mode').has_value('Doubler'), 'Notches', 'Warmth', 'Dry/Wet') }),))
CUSTOM_BANK_DEFINITIONS['Redux2'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: ('Sample Rate', 'Jitter', 'Bit Depth', use('Quantizer Shape').with_name('Shape'), use('Pre-Filter On').with_name('Pre-Filter'), use('Post-Filter On').with_name('Post-Filter'), use('Post-Filter').with_name('Post-Filter Freq'), 'Dry/Wet') }),))
CUSTOM_BANK_DEFINITIONS['Reverb'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: ('Decay Time', 'Room Size', 'Input Freq', 'Predelay', 'Stereo Image', use('LowShelf Gain').with_name('Lo Shelf Gain'), use('Diff. Hi Freq').with_name('Hi Filter Freq').if_parameter('Diff. Hi Type').has_value('Lowpass').else_use('HiShelf Gain').with_name('Hi Shelf Gain'), 'Dry/Wet') }),))
CUSTOM_BANK_DEFINITIONS['Saturator'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: ('Drive', 'Type', use('Color Amt Low').with_name('Color Low'), use('Color Freq').with_name('Color Frequency'), use('Color Width').with_name('Color Width'), use('Color Amt Hi').with_name('Color High'), 'Output', 'Dry/Wet') }),))
CUSTOM_BANK_DEFINITIONS['OriginalSimpler'] = IndexedDict(((BANK_MAIN_KEY, {
    BANK_PARAMETERS_KEY: (use('Transpose').if_shift(False).else_use('Detune'), use('Ve Attack').with_name('Attack').if_parameter('Multi Sample').has_value('On').else_use('Start').if_parameter('Mode').does_not_have_value('Slicing').else_use('Sensitivity').if_parameter('Slice by').has_value('Transient').else_use('Division').if_parameter('Slice by').has_value('Beat').else_use('Regions').if_parameter('Slice by').has_value('Region').else_use(''), use('Nudge').if_parameter('Mode').has_value('Slicing').else_use('Ve Decay').with_name('Decay').if_parameter('Multi Sample').has_value('On').else_use('Ve Attack').with_name('Attack').if_parameter('Mode').has_value('Classic').else_use('End'), use('Ve Sustain').with_name('Sustain').if_parameter('Multi Sample').has_value('On').else_use('Ve Decay').with_name('Decay').if_parameter('Mode').has_value('Classic').else_use('Fade In'), use('S Length').with_name('Playback Length').if_shift(True).and_parameter('Mode').has_value('Classic').else_use('Ve Release').with_name('Release').if_parameter('Multi Sample').has_value('On').or_parameter('Mode').has_value('Classic').else_use('Fade Out'), use('Filter Freq').with_name('Filter Frequency'), use('Filter Res').with_name('Filter Resonance'), use('Filt < LFO').with_name('Filter LFO').if_shift(False).else_use('L Rate').with_name('LFO Rate').if_parameter('L Sync').has_value('Free').else_use('L Sync Rate').with_name('LFO Rate')) }), ('Setup', {
    BANK_PARAMETERS_KEY: ('Filter Type', use('Ve Mode').with_name('Envelope Mode'), '', '', '', '', '', '') })))
